version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "drandrel-aws-cloudformation-stack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1qyvwvhbngv09"
s3_prefix = "drandrel-aws-cloudformation-stack"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
