Description: Registers the latest version of the ProServe::CloudFormation::Stack CloudFormation Resource

Parameters:
  SourceBucketName:
    Type: String
    Default: curlim
  SourceBucketPrefix:
    Type: String
    Default: release/aws-cloudformation-stack-resource
  Version:
    Type: String
    Default: v2.1.0
Resources:
  CfnLogAndMetricsDeliveryRole:
    Type: AWS::IAM::Role
    Properties:
      MaxSessionDuration: 43200
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Effect: Allow
          Principal:
            Service:
              - resources.cloudformation.amazonaws.com
          Action: sts:AssumeRole
      Path: "/"
      Policies:
      - PolicyName: LogAndMetricsDeliveryRolePolicy
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
          - Effect: Allow
            Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:DescribeLogGroups
            - logs:DescribeLogStreams
            - logs:PutLogEvents
            - cloudwatch:ListMetrics
            - cloudwatch:PutMetricData
            Resource: "*"
  CfnResourceProviderExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      MaxSessionDuration: 8400
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: resources.cloudformation.amazonaws.com
            Action: sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: ResourceTypePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                - "sts:AssumeRole"
                Resource: "*"
  CfnResourceLogGroup:
    Type: AWS::Logs::LogGroup
    Properties: 
      LogGroupName: ProServe-CloudFormation-Stack
      RetentionInDays: 30
  CfnStackCfnResourceProvider:
    Type: AWS::CloudFormation::ResourceVersion
    Properties:
      ExecutionRoleArn: !GetAtt CfnResourceProviderExecutionRole.Arn
      SchemaHandlerPackage: !Sub s3://${SourceBucketName}/${SourceBucketPrefix}/${Version}.zip
      TypeName: ProServe::CloudFormation::Stack
      LoggingConfig:
          LogGroupName: !Ref CfnResourceLogGroup
          LogRoleArn: !GetAtt CfnLogAndMetricsDeliveryRole.Arn
  CfnResourceProviderDefaultVersion:
    Type: AWS::CloudFormation::ResourceDefaultVersion
    Properties:
      TypeName: ProServe::CloudFormation::Stack
      TypeVersionArn: !Ref CfnStackCfnResourceProvider
